### ISSUE TITLE
Github actions not working

### ISSUE THREAD

**Issue by steebchen** [kamilkisiela/graphql-inspector#99]
I can't get graphql-inspector to work on my repo. I have enabled the app for my repo, and added the following in my main.workflow:

```
workflow "On Push" {
  on = "push"
  resolves = "Check GraphQL with Inspector"
}

workflow "On Pull Request" {
  on = "pull_request"
  resolves = "Check GraphQL with Inspector"
}

# Deploy and Host GraphQL Inspector
action "Check GraphQL with Inspector" {
  uses = "kamilkisiela/graphql-inspector@v0.13.3"
  secrets = ["GITHUB_TOKEN"]
}
```

package.json:
```
 "graphql-inspector": {
    "diff": true,
"schema": {
      "ref": "head/master",
      "path": "new.graphql"
    }
}
```

action debug output:

```
[before-after-hook]: "Hook()" repurposing warning, use "Hook.Collection()". Read more: https://git.io/upgrade-before-after-hook-to-1.4
01:10:02.143Z DEBUG probot: Webhook received
  event: {
    "event": "push",
    "id": "b9bf6af5-60e7-4192-9dfc-d6fbd7d1b597",
    "repository": "steebchen/test-actions"
  }
01:10:02.171Z  INFO event: GraphQL Inspector started (action: gh-action) - steebchen/test-actions#a17c5c7e3f02ea70c7690f0e34e8d2797e5f4fa6 (id=b9bf6af5-60e7-4192-9dfc-d6fbd7d1b597)
01:10:02.521Z DEBUG github: GitHub request: GET /app/installations - 401 undefined (installation=undefined)
  params: {
    "per_page": 100,
    "baseUrl": "https://api.github.com",
    "request": {
      "timeout": 0
    }
  }
01:10:02.523Z ERROR probot: Your private key (usually a .pem file) is not correct. Go to https://github.com/settings/apps/YOUR_APP and generate a new PEM file. If you're deploying to Now, visit https://probot.github.io/docs/deployment/#now.
  HttpError: {"message":"A JSON web token could not be decoded","documentation_url":"https://developer.github.com/v3"}
      at response.text.then.message (/usr/local/share/.config/yarn/global/node_modules/@octokit/rest/lib/request/request.js:72:19)
      at process._tickCallback (internal/process/next_tick.js:68:7)
01:10:02.762Z DEBUG github: GitHub request: POST https://api.github.com/repos/steebchen/test-actions/check-runs - 201 Created (installation=undefined)
  params: {
    "name": "graphql-inspector",
    "started_at": "2019-03-17T01:10:02.172Z",
    "head_sha": "a17c5c7e3f02ea70c7690f0e34e8d2797e5f4fa6",
    "status": "in_progress",
    "baseUrl": "https://api.github.com",
    "request": {
      "timeout": 0
    }
  }
01:10:02.763Z  INFO event: [check-start] sent - steebchen/test-actions#a17c5c7e3f02ea70c7690f0e34e8d2797e5f4fa6 (id=b9bf6af5-60e7-4192-9dfc-d6fbd7d1b597)
01:10:03.546Z DEBUG github: GitHub request: POST /graphql - 200 OK (installation=undefined)
  params: {
    "baseUrl": "https://api.github.com",
    "query": "\n    query GetFile($repo: String!, $owner: String!, $expression: String!) {\n      repository(name: $repo, owner: $owner) {\n        object(expression: $expression) {\n          ... on Blob {\n            text\n          }\n        }\n      }\n    }\n  ",
    "variables": {
      "repo": "test-actions",
      "owner": "steebchen",
      "expression": "a17c5c7e3f02ea70c7690f0e34e8d2797e5f4fa6:package.json"
    },
    "request": {
      "timeout": 0
    }
  }
01:10:04.572Z DEBUG github: GitHub request: POST /graphql - 200 OK (installation=undefined)
  params: {
    "baseUrl": "https://api.github.com",
    "query": "\n    query GetFile($repo: String!, $owner: String!, $expression: String!) {\n      repository(name: $repo, owner: $owner) {\n        object(expression: $expression) {\n          ... on Blob {\n            text\n          }\n        }\n      }\n    }\n  ",
    "variables": {
      "repo": "test-actions",
      "owner": "steebchen",
      "expression": "head/master:new.graphql"
    },
    "request": {
      "timeout": 0
    }
  }
01:10:04.575Z ERROR event: Cannot read property 'text' of null (id=b9bf6af5-60e7-4192-9dfc-d6fbd7d1b597)
  TypeError: Cannot read property 'text' of null
      at /usr/local/share/.config/yarn/global/node_modules/@graphql-inspector/github/dist/probot.js:57:72
      at step (/usr/local/share/.config/yarn/global/node_modules/@graphql-inspector/github/dist/probot.js:32:23)
      at Object.next (/usr/local/share/.config/yarn/global/node_modules/@graphql-inspector/github/dist/probot.js:13:53)
      at fulfilled (/usr/local/share/.config/yarn/global/node_modules/@graphql-inspector/github/dist/probot.js:4:58)
      at process._tickCallback (internal/process/next_tick.js:68:7)
  --
  event: {
    "event": "push",
    "id": "b9bf6af5-60e7-4192-9dfc-d6fbd7d1b597",
    "repository": "steebchen/test-actions"
  }

### FAILED Check GraphQL with Inspector 01:10:09Z (26.333s)
```

What can I do to fix it? Thanks in advance!

**Comment by steebchen** [comment]
reproduction available at [steebchen/test-graphql](https://github.com/steebchen/test-graphql)

**Comment by kamilkisiela** [comment]
Release in [`v1.15.0`](https://github.com/kamilkisiela/graphql-inspector/releases/tag/v1.15.0)

**Comment by steebchen** [comment]
It seems the release fixed something, but the other error still persists on v1.16.0. I'm using `.github/graphql-inspector.yml` as a config file:

```
success Installed "@graphql-inspector/actions@1.16.0" with binaries:
      - graphql-inspector-github
Done in 9.03s.
 ---> 25406fe10f51
Step 12/13 : COPY entrypoint.sh /entrypoint.sh
 ---> 71f1b9be4e28
Step 13/13 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Running in 8d042b3163db
 ---> 243759f379a4
Successfully built 243759f379a4
Successfully tagged gcr.io/gct-12-5q88qkdur-z0wx0ad3sh82r/6abc6d67166c0d85f54150a3d770d59d501f091104ca4e8aa6f4c7b0880b0a01/8a5edab282632443219e051e4ade2d1d5bbc671c781051bf1437897cbdfea0f1:af031e6178b8d2469909e6a77fe422d4b122e50947d3fe7101aacb83969c31b0
Already have image (with digest): gcr.io/github-actions-images/action-runner:latest
ℹ  info      GraphQL Inspector started
ℹ  info      Failed to find .github/graphql-inspector.yaml file
✖  fatal     TypeError: Cannot read property 'text' of null 
    at /usr/local/share/.config/yarn/global/node_modules/@graphql-inspector/actions/dist/index.js:207:72
    at step (/usr/local/share/.config/yarn/global/node_modules/@graphql-inspector/actions/dist/index.js:33:23)
    at Object.next (/usr/local/share/.config/yarn/global/node_modules/@graphql-inspector/actions/dist/index.js:14:53)
    at fulfilled (/usr/local/share/.config/yarn/global/node_modules/@graphql-inspector/actions/dist/index.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)

### FAILED Check GraphQL with Inspector 00:41:16Z (36.571s)
```

**Comment by steebchen** [comment]
@kamilkisiela just a ping to re-open this issue please :)

**Comment by kamilkisiela** [comment]
Could you try `v1.18.0`?

**Comment by kamilkisiela** [comment]
I see now what's going on. You get

> ℹ  info      Failed to find .github/graphql-inspector.yaml file

which is something fixed in https://github.com/kamilkisiela/graphql-inspector/commit/ddf097e104269e2e6dbb47fb679795eae20f8b69

**Comment by steebchen** [comment]
That's not the issue. I have a .yml file and not a .yaml, thus the info log is correct.

On v1.18.0, I still get the following error:

```
Successfully built 2e8af86231ed
Successfully tagged gcr.io/gct-12-5q88qkdur-z0wx0ad3sh82r/6abc6d67166c0d85f54150a3d770d59d501f091104ca4e8aa6f4c7b0880b0a01/8a5edab282632443219e051e4ade2d1d5bbc671c781051bf1437897cbdfea0f1:2fdcb94ea712d851c5bcb866d222de14b85c47e3faa70f16a72af1da490fda51
Already have image (with digest): gcr.io/github-actions-images/action-runner:latest
ℹ  info      GraphQL Inspector started
ℹ  info      Failed to find .github/graphql-inspector.yaml file
✖  fatal     TypeError: Cannot read property 'text' of null 
    at /usr/local/share/.config/yarn/global/node_modules/@graphql-inspector/actions/dist/index.js:204:72
    at step (/usr/local/share/.config/yarn/global/node_modules/@graphql-inspector/actions/dist/index.js:44:23)
    at Object.next (/usr/local/share/.config/yarn/global/node_modules/@graphql-inspector/actions/dist/index.js:25:53)
    at fulfilled (/usr/local/share/.config/yarn/global/node_modules/@graphql-inspector/actions/dist/index.js:16:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)

### FAILED Check GraphQL with Inspector 11:41:40Z (36.813s)
```

**Comment by kamilkisiela** [comment]
Could you bump to `v1.18.1`? I tried it and I think it's no longer an issue. Checked both with `.github/graphql-inspector.yml` and `.github/graphql-inspector.yaml` files.

**Comment by steebchen** [comment]
Thanks for re-opening. This went on for so long that I don't even know anymore if this is maybe my issue, but I wouldn't know what. New logs with v1.18.1:

```
success Installed "@graphql-inspector/actions@1.18.1" with binaries:
      - graphql-inspector-github
Done in 9.35s.
 ---> 4b99056e70a9
Step 12/13 : COPY entrypoint.sh /entrypoint.sh
 ---> 10bf22e29b7f
Step 13/13 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Running in 38f99e43ac15
 ---> 9af425228f33
Successfully built 9af425228f33
Successfully tagged gcr.io/gct-12-5q88qkdur-z0wx0ad3sh82r/6abc6d67166c0d85f54150a3d770d59d501f091104ca4e8aa6f4c7b0880b0a01/8a5edab282632443219e051e4ade2d1d5bbc671c781051bf1437897cbdfea0f1:2c3bde79909df4dfc6c91597167c9cf1e17717e572877c239e1596ff97cc3b42
Already have image (with digest): gcr.io/github-actions-images/action-runner:latest
TypeError: Cannot read property 'text' of null
    at /usr/local/share/.config/yarn/global/node_modules/@graphql-inspector/actions/dist/index.js:205:76
    at step (/usr/local/share/.config/yarn/global/node_modules/@graphql-inspector/actions/dist/index.js:44:23)
    at Object.next (/usr/local/share/.config/yarn/global/node_modules/@graphql-inspector/actions/dist/index.js:25:53)
    at fulfilled (/usr/local/share/.config/yarn/global/node_modules/@graphql-inspector/actions/dist/index.js:16:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
ℹ  info      GraphQL Inspector started
{ repository: { object: null } }
ℹ  info      Failed to find .github/graphql-inspector.yaml file
{ repository: { object: null } }
✖  fatal     Error: Failed to load 'new.graphql' (ref: head/master) 
    at /usr/local/share/.config/yarn/global/node_modules/@graphql-inspector/actions/dist/index.js:210:35
    at step (/usr/local/share/.config/yarn/global/node_modules/@graphql-inspector/actions/dist/index.js:44:23)
    at Object.next (/usr/local/share/.config/yarn/global/node_modules/@graphql-inspector/actions/dist/index.js:25:53)
    at fulfilled (/usr/local/share/.config/yarn/global/node_modules/@graphql-inspector/actions/dist/index.js:16:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
TypeError: Cannot read property 'text' of null
    at /usr/local/share/.config/yarn/global/node_modules/@graphql-inspector/actions/dist/index.js:205:76
    at step (/usr/local/share/.config/yarn/global/node_modules/@graphql-inspector/actions/dist/index.js:44:23)
    at Object.next (/usr/local/share/.config/yarn/global/node_modules/@graphql-inspector/actions/dist/index.js:25:53)
    at fulfilled (/usr/local/share/.config/yarn/global/node_modules/@graphql-inspector/actions/dist/index.js:16:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)

### FAILED Check GraphQL with Inspector 20:24:40Z (37.108s)
```

.github/icon graphql-inspector.yml
```yml
diff: true
schema:
  ref: head/master
path: new.graphql
```

new.graphql
```graphql
type User {
	id: ID!
	email: String!
	firstName: String!
	lastName: String
	wazzup: String!
}
```

**Comment by kamilkisiela** [comment]
Ooohh ok, I think you can turn `head/master` to just `master` and it should work. I don't know why but somehow `head/something` doesn't work in Github API any more.

**Comment by steebchen** [comment]
Yesss, that worked! Thanks so much for the help.

**Comment by steebchen** [comment]
Just FYI, the error above is still showing:

```
TypeError: Cannot read property 'text' of null
    at /usr/local/share/.config/yarn/global/node_modules/@graphql-inspector/actions/dist/index.js:205:76
    at step (/usr/local/share/.config/yarn/global/node_modules/@graphql-inspector/actions/dist/index.js:44:23)
    at Object.next (/usr/local/share/.config/yarn/global/node_modules/@graphql-inspector/actions/dist/index.js:25:53)
    at fulfilled (/usr/local/share/.config/yarn/global/node_modules/@graphql-inspector/actions/dist/index.js:16:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Everything is working as expected though now, so feel free to close.

**Comment by kamilkisiela** [comment]
That's the expected behavior right now, just to see what's the reason behind failed file loading, so instead of seeing "File a.yml couldn't be found" we see why is that. I might change it in the future so it won't "scream" that loud in action's log.
